print('User Details')
fname = input("Enter fname:")
lname = input("Enter lname: ")
dob = input("Enter date of birth: ")
addr = input("Enter address: ")
email = input("Enter email: ")
sex = input("Enter sex: ")